import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";

const inter = Lato({
  weight: ["100", "300", "400", "700"],
  subsets: ["latin-ext"],
});

export const metadata: Metadata = {
  title: "Weather Forecast",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`bg-cover bg-center bg-background-card overflow-y-auto min-h-screen ${inter.className}`}
        style={{ backgroundImage: "url('/background.png')" }}
      >
        {children}
      </body>
    </html>
  );
}
